---
title: Turtley Amazing
hero_image: images/banner.png
description: In this resource you will take your first steps with the programming
  language Python
original_url: https://raspberrypi.org/learning/turtley-amazing
theme: violet
duration: 2
listed: false
copyedit: false
last_tested: "2026-01-26"
copyedit: false
last_tested: "2026-01-26"
steps:
- title: Step 1
- title: Step 2
  completion:
  - engaged
- title: Step 3
- title: Step 4
- title: Step 5
- title: Step 6
- title: Step 7
- title: Step 8
  completion:
  - internal
  - external
