---
title: Turtley Amazing
hero_image: images/banner.png
description: In this resource you will take your first steps with the programming
  language Python
original_url: https://raspberrypi.org/learning/turtley-amazing
theme: violet
duration: 2
listed: false
copyedit: false
last_tested: "2026-01-26"
copyedit: false
last_tested: "2026-01-26"
landing: true
steps:
  - title: Draw a line
  - title: Turning
    completion:
      - engaged
  - title: Draw a rectangle
  - title: Speedy colour!
  - title: Draw a spiral of shapes
    completion:
      - internal
  - title: Multi-colour spiral
    completion:
      - external
  - title: "Challenge: Tighter turns"
    challenge: true
